/*
 * Implementation file for EXAMPLE-COUNTERS application.
 * Copyright (C) 2018-2019 Anderson Domingues, <ti.andersondomingues@gmail.com>
 * This file is part of project URSA (http://https://github.com/andersondomingues/ursa).
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */
 
#include "float-mult.h"
#include "orca-hardware-counters.h"

// address of the external floating point multiplier
#define MULT_RESULT		(volatile uint32_t*)0xf0000100
#define MULT_OP1		(volatile uint32_t*)0xf0000104
#define MULT_OP2		(volatile uint32_t*)0xf0000108


float mult(const float op1, const float op2){
	*MULT_OP1 = op1;
	*MULT_OP2 = op2;
	return *MULT_RESULT;
}

/*
// union used to 'convert' float to int and int to float
union Data {
   int i;
   float f;
} ; 
*/

void float_mult(void){
	/*
	union Data op1; 
	union Data op2_copy; 
	union Data op2; 
	union Data out_ext; 
	union Data out_int;
*/
	float op1; 
	float op2_copy;
	float op2; 
	float out_ext; 
	float out_int;
	// uint pointers to the float vars
	uint32_t * op1_i;
	uint32_t * op2_i;
	uint32_t * out_ext_i;
	uint32_t * op2_copy_i;

	int8_t sop1[10];
	int8_t sop2_copy[10];
	int8_t sop2[10];
	int8_t sout_ext[50];
	int8_t sout_int[50];

	int i=0;

	op1 = 10.0;
	op2 = 5.0;
	// uint pointers to the float vars
	op1_i = (uint32_t *) &op1;
	op2_i = (uint32_t *) &op2;
	out_ext_i = (uint32_t *) &out_ext;
	op2_copy_i = (uint32_t *) &op2_copy;


    while (i<50){
		ftoa(op1,sop1,2);
		ftoa(op2,sop2,2);
		// get the multiplication value from the external multiplier
		//out_ext.i = mult(op1.i, op2.i);  // older implementation with union
		*out_ext_i = mult(*op1_i, *op2_i); 

		// it is expected to have op2_copy == op2
		*op2_copy_i =  *MULT_OP2;
		ftoa(op2_copy,sop2_copy,2);
	
		// this is the reference output, generated by the internal multiplier
		out_int = op1*op2;
		ftoa(out_ext,sout_ext,6);
		ftoa(out_int,sout_int,6);

		// show the result from both external and internal multipliers
		printf("Result: %s x %s = %s != %s\n", sop1, sop2, sout_ext, sout_int );
		// the value of f2_copy and f2 should be equal 
		printf("Result: %s = %s\n", sop2, sop2_copy );

		op2 += 0.1;

		delay_ms(1);
		i++;
	}

	printf("MEM0: writes=%u, reads=%u\n", *M0_COUNTER_STORE, *M0_COUNTER_LOAD);
	printf("MEM1: writes=%u, reads=%u\n", *M1_COUNTER_STORE, *M1_COUNTER_LOAD);
	printf("MEM2: writes=%u, reads=%u\n", *M2_COUNTER_STORE, *M2_COUNTER_LOAD);
	printf("---\n");

	printf("CPU: arith=%u, logical=%u\n",   *CPU_COUNTER_ARITH, *CPU_COUNTER_LOGICAL);
	printf("CPU: shift=%u, branches=%u\n",  *CPU_COUNTER_SHIFT, *CPU_COUNTER_BRANCHES);
	printf("CPU: jumps=%u, loadstore=%u\n", *CPU_COUNTER_JUMPS, *CPU_COUNTER_LOADSTORE);
	printf("CPU: cycles=%u, stalls=%u\n", *CPU_COUNTER_CYCLES_TOTAL, *CPU_COUNTER_CYCLES_STALL);	
	printf("CPU: hosttime=%u\n", *CPU_COUNTER_HOSTTIME);
	printf("---\n");

	hf_kill(hf_selfid());
}
