/*
 * Implementation file for EXAMPLE-COUNTERS application.
 * Copyright (C) 2018-2019 Anderson Domingues, <ti.andersondomingues@gmail.com>
 * This file is part of project URSA (http://https://github.com/andersondomingues/ursa).
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */

#ifdef __cplusplus  
extern "C" { 
#endif 

#include "cpp-float-mult.h"
#include "orca-hardware-counters.h"

// address of the external floating point multiplier
#define MULT_RESULT		 (volatile uint32_t*)0xf0000100
#define MULT_OP1		 (volatile uint32_t*)0xf0000104
#define MULT_OP2		 (volatile uint32_t*)0xf0000108

// union used to 'convert' float to int and int to float
union Data {
   int i;
   float f;
} ; 

class MyFloat { 
public: 
    union Data data; 
	// ctor
    MyFloat(union Data d) {data = d;}
	MyFloat(MyFloat& p) {data = p.data;}
	MyFloat() {data.f = 0.0;}

    // This is automatically called when '+' is used with 
    // between two Complex objects 
	void operator = (const MyFloat& p)
	{	//char s1[10], s2[10];
		data = p.data;
		//str(s1,4);
		//p.str(s2,4);
		//printf("Recebi MyFloat: %s - %s \n", s1, s2 );
	}

	void operator = (const union Data d)
	{	//char s1[10], s2[10];
		data = d;
		//str(s1,4);
		//ftoa(d.f,s2,4);
		//printf("Recebi union: %s - %s \n", s1, s2 );
	}

	void operator = (const float d)
	{	//char s1[10], s2[10];
		data.f = d;
		//str(s1,4);
		//ftoa(d,s2,4);
		//printf("Recebi float: %s - %s \n", s1, s2 );
	}

/*
	// Overloading the postfix operator 
	MyFloat operator ++(union Data) 
	{	MyFloat x;
		x.SetData(++data);
		return x;
	}
*/
	friend MyFloat operator + ( MyFloat& op1,  MyFloat& op2) { 
		MyFloat res;
		res = op1 + op2;
		return res; 
	} 
/*
	friend MyFloat operator + ( const MyFloat& op1,  const float op2) { 
		MyFloat res;
		res.data.f = op1.data.f + op2;
		return res; 
	} 
*/
	void str( char *s, const uint8_t precision) const{
		ftoa(data.f,s,precision);
	}

	friend MyFloat operator * ( MyFloat& op1,  MyFloat& op2) { 
		MyFloat res; 
		//char s1[30], s2[30], s3[30];
		*MULT_OP1 = op1.data.i;
		*MULT_OP2 = op2.data.i;
		//res.data = MULT_RESULT;
		res.data.i = *MULT_RESULT;
		//op1.str(s1,8);
		//op2.str(s2,8);
		//res.str(s3,8);
		//printf("Result3: %s x %s = %s\n", s1, s2, s3 );
		return res; 
	} 
	//union Data GetData(){return data;}
	//void SetData(union Data d){data = d;}
	//void SetData(MyFloat m){data = m.data;}
}; 

void cpp_float_mult(void){
	MyFloat op1; 
	MyFloat op2_copy;
	MyFloat op2; 
	MyFloat out_ext; 
	MyFloat out_int;
	MyFloat inc; 

	int8_t sop1[10];
	int8_t sop2_copy[10];
	int8_t sop2[10];
	int8_t sout_ext[50];
	int8_t sout_int[50];

	int i=0;

	op1 = 10.0;
	op2 = 5.0;

    while (i<50){
		op1.str(sop1,2);
		op2.str(sop2,2);
		// get the multiplication value from the external multiplier
		out_ext = op1 * op2; 

		// reading back the last value written in OP2. it is expected to have op2_copy == op2
		op2_copy.data.i =  *MULT_OP2;
		op2_copy.str(sop2_copy,2);
	
		// this is the reference output, generated by the internal multiplier
		out_int.data.f = op1.data.f*op2.data.f;

		// converting both the external and the internal mult results into str
		out_ext.str(sout_ext,8);
		out_int.str(sout_int,8);

		// show the result from both external and internal multipliers
		printf("Result: %s x %s = %s == %s\n", sop1, sop2, sout_ext, sout_int );
		// the value of f2_copy and f2 should be equal 
		printf("Result: %s == %s\n", sop2, sop2_copy );

		op2.data.f += 0.1;
		//op2 = op2 + inc;

		delay_ms(1);
		i++;
	}

	printf("MEM0: writes=%u, reads=%u\n", *M0_COUNTER_STORE, *M0_COUNTER_LOAD);
	printf("MEM1: writes=%u, reads=%u\n", *M1_COUNTER_STORE, *M1_COUNTER_LOAD);
	printf("MEM2: writes=%u, reads=%u\n", *M2_COUNTER_STORE, *M2_COUNTER_LOAD);
	printf("---\n");

	printf("CPU: arith=%u, logical=%u\n",   *CPU_COUNTER_ARITH, *CPU_COUNTER_LOGICAL);
	printf("CPU: shift=%u, branches=%u\n",  *CPU_COUNTER_SHIFT, *CPU_COUNTER_BRANCHES);
	printf("CPU: jumps=%u, loadstore=%u\n", *CPU_COUNTER_JUMPS, *CPU_COUNTER_LOADSTORE);
	printf("CPU: cycles=%u, stalls=%u\n", *CPU_COUNTER_CYCLES_TOTAL, *CPU_COUNTER_CYCLES_STALL);	
	printf("CPU: hosttime=%u\n", *CPU_COUNTER_HOSTTIME);
	printf("---\n");

	hf_kill(hf_selfid());
}

#ifdef __cplusplus 
} 
#endif 